# Generated by Django 6.0.6 on 2026-06-16 09:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('batch_no', models.CharField(default=0, max_length=200)),
                ('stock', models.IntegerField(default=0)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('condition', models.CharField(max_length=200)),
                ('demographics', models.CharField(max_length=200)),
                ('email', models.EmailField(default='Unknown', max_length=254)),
                ('allergies', models.CharField(default='None', max_length=200)),
                ('blood_type', models.CharField(choices=[('A', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='Unknown', max_length=3)),
                ('phone_no', models.IntegerField(default=0)),
                ('register_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=10)),
                ('frequency', models.CharField(max_length=50)),
                ('date_prescribed', models.DateField()),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.patient')),
            ],
        ),
    ]
