# Generated by Django 6.0.6 on 2026-06-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('Male', 'Female'), ('Male', 'Female')], default='Unknown', max_length=7),
        ),
    ]
