# Generated by Django 6.0.6 on 2026-06-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_patient_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Unknown', max_length=7),
        ),
    ]
